# Banking Fraud & Risk Analytics Platform

### Objective

The objective of this notebook is to clean and prepare the Accounts and Transactions datasets for analysis while preserving data integrity.

This notebook focuses on:

- Creating working copies of the original datasets
- Standardizing column names for better readability
- Converting columns to appropriate data types
- Handling missing values (if any)
- Removing duplicate records (if present)
- Validating data consistency after cleaning
- Preparing clean datasets for feature engineering and exploratory data analysis
- Exporting the cleaned datasets for downstream analysis

## Importing All Required Libraries

In [3]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)

## Loading the dataset

In [4]:
accounts = pd.read_csv("../data/raw/accounts.csv")
transactions = pd.read_csv("../data/raw/Trans.csv")

## Creating Copy of Dataset

In [6]:
account_clean=accounts.copy()
transactions_clean=transactions.copy()

In [8]:
account_clean.isna().sum()

Bank Name         0
Bank ID           0
Account Number    0
Entity ID         0
Entity Name       0
dtype: int64

In [9]:
transactions_clean.isna().sum()

Timestamp             0
From Bank             0
Account               0
To Bank               0
Account.1             0
Amount Received       0
Receiving Currency    0
Amount Paid           0
Payment Currency      0
Payment Format        0
Is Laundering         0
dtype: int64

## Missing Value Analysis

Both the Accounts and Transactions datasets contain **no missing values** across all columns.

### Findings

- No null values were detected.
- All mandatory fields are complete.
- No imputation techniques are required.
- The datasets are complete and suitable for further processing.

In [10]:
account_clean.duplicated().sum()

np.int64(0)

In [12]:
transactions_clean.duplicated().sum()

np.int64(9)

## Duplicate Record Analysis

### Accounts Dataset

- Duplicate Records: **0**
- Every account record appears to be unique.

### Transactions Dataset

- Duplicate Records: **9**

The Transactions dataset contains a small number of duplicate records.

These records will be investigated further before deciding whether they should be removed, as duplicate transactions may represent either data quality issues or legitimate repeated financial transactions.

In [13]:
transactions_clean[transactions_clean.duplicated()]

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
863295,2022/09/01 16:20,12004,800C927C1,12004,800C927C0,0.000008,Bitcoin,0.080000,Euro,ACH,0
863296,2022/09/01 16:20,12004,800C927C1,220,813D8C1E1,0.000008,Bitcoin,0.000008,Bitcoin,Bitcoin,0
3684005,2022/09/07 21:25,29992,8099A29B1,220,813725AE1,0.000003,Bitcoin,0.000003,Bitcoin,Bitcoin,0
4166786,2022/09/08 21:05,113779,811144AB1,113779,811144AB0,0.000002,Bitcoin,0.020000,US Dollar,ACH,0
4166787,2022/09/08 21:05,113779,811144AB1,53744,813C777F1,0.000002,Bitcoin,0.000002,Bitcoin,Bitcoin,0
4510480,2022/09/09 10:03,6075,80C702911,6075,80C702910,0.000002,Bitcoin,0.020000,US Dollar,ACH,0
4510481,2022/09/09 10:03,6075,80C702911,154653,814389B61,0.000002,Bitcoin,0.000002,Bitcoin,Bitcoin,0
4816512,2022/09/09 21:33,14433,80935A891,14433,80935A890,0.000001,Bitcoin,0.010000,US Dollar,ACH,0
4816513,2022/09/09 21:33,14433,80935A891,15,813F7AE61,0.000001,Bitcoin,0.000001,Bitcoin,Bitcoin,0

In [14]:
transactions_clean[transactions_clean.duplicated(keep=False)]

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
863293,2022/09/01 16:20,12004,800C927C1,12004,800C927C0,0.000008,Bitcoin,0.080000,Euro,ACH,0
863294,2022/09/01 16:20,12004,800C927C1,220,813D8C1E1,0.000008,Bitcoin,0.000008,Bitcoin,Bitcoin,0
863295,2022/09/01 16:20,12004,800C927C1,12004,800C927C0,0.000008,Bitcoin,0.080000,Euro,ACH,0
863296,2022/09/01 16:20,12004,800C927C1,220,813D8C1E1,0.000008,Bitcoin,0.000008,Bitcoin,Bitcoin,0
3684003,2022/09/07 21:25,29992,8099A29B1,220,813725AE1,0.000003,Bitcoin,0.000003,Bitcoin,Bitcoin,0
3684005,2022/09/07 21:25,29992,8099A29B1,220,813725AE1,0.000003,Bitcoin,0.000003,Bitcoin,Bitcoin,0
4166784,2022/09/08 21:05,113779,811144AB1,113779,811144AB0,0.000002,Bitcoin,0.020000,US Dollar,ACH,0
4166785,2022/09/08 21:05,113779,811144AB1,53744,813C777F1,0.000002,Bitcoin,0.000002,Bitcoin,Bitcoin,0
4166786,2022/09/08 21:05,113779,811144AB1,113779,811144AB0,0.000002,Bitcoin,0.020000,US Dollar,ACH,0
4166787,2022/09/08 21:05,113779,811144AB1,53744,813C777F1,0.000002,Bitcoin,0.000002,Bitcoin,Bitcoin,0
4510478,2022/09/09 10:03,6075,80C702911,6075,80C702910,0.000002,Bitcoin,0.020000,US Dollar,ACH,0
4510479,2022/09/09 10:03,6075,80C702911,154653,814389B61,0.000002,Bitcoin,0.000002,Bitcoin,Bitcoin,0
4510480,2022/09/09 10:03,6075,80C702911,6075,80C702910,0.000002,Bitcoin,0.020000,US Dollar,ACH,0
4510481,2022/09/09 10:03,6075,80C702911,154653,814389B61,0.000002,Bitcoin,0.000002,Bitcoin,Bitcoin,0
4816510,2022/09/09 21:33,14433,80935A891,14433,80935A890,0.000001,Bitcoin,0.010000,US Dollar,ACH,0
4816511,2022/09/09 21:33,14433,80935A891,15,813F7AE61,0.000001,Bitcoin,0.000001,Bitcoin,Bitcoin,0
4816512,2022/09/09 21:33,14433,80935A891,14433,80935A890,0.000001,Bitcoin,0.010000,US Dollar,ACH,0
4816513,2022/09/09 21:33,14433,80935A891,15,813F7AE61,0.000001,Bitcoin,0.000001,Bitcoin,Bitcoin,0

## Droping the dupilcates

In [15]:
transactions_clean = transactions_clean.drop_duplicates()

In [16]:
transactions_clean.duplicated().sum()

np.int64(0)

## Duplicate Record Handling

During the data quality assessment, the Transactions dataset was found to contain **9 duplicate records**.

A detailed investigation was performed by displaying both the original and duplicate entries using `duplicated(keep=False)`.

The comparison confirmed that each duplicate pair was **identical across all 11 columns**, indicating that these were duplicate observations rather than legitimate repeated transactions.

To maintain data integrity and prevent double-counting during analysis, the duplicate records were removed from the dataset.

The Accounts dataset did not contain any duplicate records.

## Standardize Column Names

To improve readability, maintain consistency, and simplify coding, the column names are standardized using the **snake_case** naming convention.

This makes the dataset easier to work with in Python, SQL, and Power BI while following common data engineering and analytics best practices.

In [17]:
transactions_clean.rename(
    columns={
        "Timestamp": "timestamp",
        "From Bank": "from_bank",
        "Account": "sender_account",
        "To Bank": "to_bank",
        "Account.1": "receiver_account",
        "Amount Received": "amount_received",
        "Receiving Currency": "receiving_currency",
        "Amount Paid": "amount_paid",
        "Payment Currency": "payment_currency",
        "Payment Format": "payment_format",
        "Is Laundering": "is_laundering"
    },
    inplace=True
)

In [19]:
account_clean.rename(
    columns={
        "Bank Name": "bank_name",
        "Bank ID": "bank_id",
        "Account Number": "account_number",
        "Entity ID": "entity_id",
        "Entity Name": "entity_name"
    },
    inplace=True
)

In [21]:
print("Account columns :",account_clean.columns)
print("Transactions columns :",transactions_clean.columns)

Account columns : Index(['bank_name', 'bank_id', 'account_number', 'entity_id', 'entity_name'], dtype='str')
Transactions columns : Index(['timestamp', 'from_bank', 'sender_account', 'to_bank',
       'receiver_account', 'amount_received', 'receiving_currency',
       'amount_paid', 'payment_currency', 'payment_format', 'is_laundering'],
      dtype='str')

In [22]:
transactions_clean["timestamp"] = pd.to_datetime(
    transactions_clean["timestamp"]
)

## Final Validation

In [23]:
transactions_clean.info()

<class 'pandas.DataFrame'>
Index: 5078336 entries, 0 to 5078344
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   timestamp           datetime64[us]
 1   from_bank           int64
 2   sender_account      str
 3   to_bank             int64
 4   receiver_account    str
 5   amount_received     float64
 6   receiving_currency  str
 7   amount_paid         float64
 8   payment_currency    str
 9   payment_format      str
 10  is_laundering       int64
dtypes: datetime64[us](1), float64(2), int64(3), str(5)
memory usage: 663.8 MB

In [26]:
transactions_clean.info()
print("-" * 50)
account_clean.info()

<class 'pandas.DataFrame'>
Index: 5078336 entries, 0 to 5078344
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   timestamp           datetime64[us]
 1   from_bank           int64
 2   sender_account      str
 3   to_bank             int64
 4   receiver_account    str
 5   amount_received     float64
 6   receiving_currency  str
 7   amount_paid         float64
 8   payment_currency    str
 9   payment_format      str
 10  is_laundering       int64
dtypes: datetime64[us](1), float64(2), int64(3), str(5)
memory usage: 663.8 MB
--------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 518581 entries, 0 to 518580
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   bank_name       518581 non-null  str
 1   bank_id         518581 non-null  int64
 2   account_number  518581 non-null  str
 3   entity_id       518581 non-null  str
 4   entity_name     518581 non-null  str
dtypes: int64(1), str(4)
memory usage: 47.3 MB

In [28]:
transactions_clean.isnull().sum()

timestamp             0
from_bank             0
sender_account        0
to_bank               0
receiver_account      0
amount_received       0
receiving_currency    0
amount_paid           0
payment_currency      0
payment_format        0
is_laundering         0
dtype: int64

In [30]:
account_clean.isnull().sum()

bank_name         0
bank_id           0
account_number    0
entity_id         0
entity_name       0
dtype: int64

In [31]:
transactions_clean.duplicated().sum()

np.int64(0)

## Exporting Dataset

In [32]:
account_clean.to_csv(
    "../data/processed/cleaned_accounts.csv",
    index=False
)

In [33]:
transactions_clean.to_csv(
    "../data/processed/cleaned_transaction.csv",
   index=False
)